reg_url = 'https://b2c.passport.rt.ru/auth/realms/b2c/login-actions/registration?client_id=account_b2c&tab_id=mSlyJ3BXU-M'
auth_url = 'https://b2c.passport.rt.ru'
valid_email = 'eodav@mailto.plus'
valid_password = 'balagaN_35'
invalid_password = 'balagaN_00'
first_name = 'Глафира'
last_name = 'Потапова'
